# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Released
on:
  release:
    types:
      - released

jobs:
  delete-pre-releases:
    name: Delete other pre-releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0

      - name: Delete other pre-releases
        shell: pwsh
        run: |
          $release = "${{ github.ref_name }}"
          $repo = "${{ github.repository }}"
          $token = "${{ secrets.GITHUB_TOKEN }}"

          # example: "bulk-client-v6.0.1"
          $packageName = ($release -split "-v")[0]

          $page = 1
          $release_list = @()

          do {

            $url = "https://api.github.com/repos/$repo/releases?per_page=100&page=$page"
            $gh_headers = @{
                "Accept"        = "application/vnd.github+json"
                "Authorization" = "Bearer $token"
            }

            $release_list = Invoke-RestMethod $url -Headers $gh_headers

            $release_list | ForEach-Object {
                if ($_.tag_name -like "$($packageName)-*" -and $_.prerelease) {
                    "Deleting pre-release $($_.tag_name)" | Out-Host
                    Invoke-RestMethod -Method Delete -Uri $_.url -Headers $gh_headers
                }
            }

            $page += 1
          } While ($release_list.count -gt 0)
