# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pre-Release
on:
  release:
    types: [published]

jobs:
  publish:
    # This is a work-around. "on.release.types = prereleased" only triggers when the
    # prerelease is created in the UI, for unknown reasons. Therefore trigger on
    # "published" event but then restrict the job to run only if it is a prerelease.
    if: github.event.release.prerelease == true

    name: Publish Pre-Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0

      - name: Hello World
        run: echo "hello world"

      # This is just a demonstration, there is no action to take. In a "real
      # repository", this would have the build, package, and publish steps in
      # it, including creationg of SBOM and provenance.
